FROM python:3.8

RUN apt-get update

WORKDIR /
RUN git clone https://github.com/celsiustx/dask.git
WORKDIR dask
RUN git checkout sum-crash  # One commit on top of Dask 2.16.0, that adds a single .ipynb added to demonstrate the crash (as well as this Dockerfile)
#RUN apt-get install -y libblas3 liblapack3 liblapack-dev libblas-dev gfortran
RUN pip install -e .[array]
RUN pytest -v
RUN pip install papermill
CMD papermill sum-crash.ipynb crashed.ipynb || echo 'crashed, as expected!'
