ARG dask_version
FROM runsascoded/dask-test:"$dask_version"

RUN pip install papermill ipykernel jupyter
RUN python -m ipykernel install --user --name 3.8.2
#ENTRYPOINT jupyter notebook
ADD sum-crash.ipynb ./
ADD sum-crash.sh ./
ENTRYPOINT ["./sum-crash.sh"]
CMD ["--port", "8889"]
